#############################################################################
# Makefile for building: bin2int
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  bin2int.pro
# Template: app
# Command: /home/kaiyin/Qt5/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile bin2int.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -D_FILE_OFFSET_BITS=64 -g -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt5/5.3/gcc_64/mkspecs/linux-g++ -I. -I/usr/include/c++/4.8 -I/usr/include/boost
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/kaiyin/Qt5/5.3/gcc_64
LIBS          = $(SUBLIBS) -lboost_system -lboost_filesystem 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kaiyin/Qt5/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/lex.prf \
		bin2int.pro main.cpp
QMAKE_TARGET  = bin2int
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = bin2int


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bin2int.pro ../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/lex.prf \
		bin2int.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile bin2int.pro
../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/yacc.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/lex.prf:
bin2int.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile bin2int.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/bin2int1.0.0 || mkdir -p .tmp/bin2int1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/bin2int1.0.0/ && (cd `dirname .tmp/bin2int1.0.0` && $(TAR) bin2int1.0.0.tar bin2int1.0.0 && $(COMPRESS) bin2int1.0.0.tar) && $(MOVE) `dirname .tmp/bin2int1.0.0`/bin2int1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bin2int1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/include/c++/4.8/iostream \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

